### ISSUE TITLE
很有用的CSS集合

### ISSUE THREAD

**Issue by hhuangxm** [hhuangxm/hhuangxm.github.io#18]
# 1.  文本省略

- 单行文本省略
```css
{
    width: 200px;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}
```
- 多行文本省略
```css
{
    width: 200px;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
}
```
